version: '2'

services:
  mongo:
    image: mongo:3.3
    ports:
      - 27017:27017

  keystone-god:
    image: keystone-god:1.0.1
    ports:
      - 30030:3000
    depends_on:
      - mongo
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
