version: '2'

services:
  mongo:
    image: mongo:3.3
    ports:
      - 27017:27017

  echo-moment:
    image: echo-gold:1.0.0
    ports:
      - 8080:8080
    depends_on:
      - mongo
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
